spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost
      database: ecommerce

aws:
  region: us-east-1
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com/337328321041/processed-orders-queue
  sns:
    orders-topic: arn:aws:sns:us-east-1:337328321041:orders-topic