spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost
      database: payments

aws:
  region: us-east-1
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com/337328321041/orders-queue
  sns:
    processed-payments-topic: arn:aws:sns:us-east-1:337328321041:processed-payments-topic

server:
  port: 8081